### PR TITLE
add asterisk rotating on scroll & add logo interaction

### PR DESCRIPTION
**Pull request by xyfeng**
add asterisk rotating on 'download' page and 'reference' page within scroll.js
add logo interaction on mouse hover

### CODE REVIEW

**Comment by xyfeng** [comment]
Yeah!

**Comment by lmccart** [comment]
so hot!! one thing, I added the cursor back into the sketch here:
https://github.com/processing/p5.js-website/commit/6023849e0f75d1a0832f43929d863639f2df2d4a

the logo is a shortcut link to the homepage, so I felt like it was important that people felt it was clickable. is this ok with you?

**Comment by xyfeng** [comment]
Not a problem at all!
I forgot it's a button ;)

-xy

On Tue, Jun 2, 2015 at 10:23 PM, Lauren McCarthy <notifications@github.com>
wrote:

> so hot!! one thing, I added the cursor back into the sketch here:
> 6023849
> <https://github.com/processing/p5.js-website/commit/6023849e0f75d1a0832f43929d863639f2df2d4a>
>
> the logo is a shortcut link to the homepage, so I felt like it was
> important that people felt it was clickable. is this ok with you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/133#issuecomment-108163857>
> .
>



-- 
 @xy_feng <http://twitter.com/xy_feng>
 xystudio.cc

**Comment by lmccart** [comment]
hm, so the other thing I notice is that it seems like performance of the homepage sketch takes a hit with this logo. I guess that makes sense, running two sketches at the same time will be slower. so I guess we could have the animated logo on all pages but the homepage, and use the static one there. how do you feel about this? I know it's not ideal, but I'm not sure what to do about performance, I feel like we don't want the first impression to be too crunchy.

**Comment by xyfeng** [comment]
Agreed on the performance. A temporary solution:

Display image at the beginning, load and hide logo sketch; use a timer or
callback to swap out of the image. We may want to set the parent div with
fixed width and height in case the content shifts.

The code may get messy. It's kind of nice to see it on all pages, however,
I'm totally ok with displaying it only on other pages as well.


-xy


On Tue, Jun 2, 2015 at 10:35 PM, Lauren McCarthy <notifications@github.com>
wrote:

> hm, so the other thing I notice is that it seems like performance of the
> homepage sketch takes a hit with this logo. I guess that makes sense,
> running two sketches at the same time will be slower. so I guess we could
> have the animated logo on all pages but the homepage, and use the static
> one there. how do you feel about this? I know it's not ideal, but I'm not
> sure what to do about performance, I feel like we don't want the first
> impression to be too crunchy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/133#issuecomment-108166153>
> .
>



-- 
 @xy_feng <http://twitter.com/xy_feng>
 xystudio.cc

**Comment by lmccart** [comment]
Ok, I've set it up to not display on the homepage. I also added a little swap out with the svg image so we don't see a jump as we wait for sketch to load. I'm not sure I understand what you mean by timer though.. I'm open to any solution for the homepage as long as it doesn't make the featured sketch slow down too much.

**Pull request merged**
