### PR TITLE
Add webp as accepted file formats

### PR DESCRIPTION
**Pull request by starzonmyarmz**
`saveCanvas()` does allow you to save the canvas as a `webp` file. I think the documentation should reflect this.

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @starzonmyarmz! I'm tagging the reference technical writer @nickmcintyre to take a look at this.
Also, to make changes on p5.js reference, we will need to make a pull request on [p5.js library](https://github.com/processing/p5.js) repo. In this case, the documentation for `saveCanvas()` is [here](https://github.com/processing/p5.js/blob/v1.9.4/src/image/image.js#L153).

**Comment by nickmcintyre** [comment]
Good catch @starzonmyarmz!

When you make the pull request in the p5.js library repo, please also have a look at the `mimeType` variable declared on line 312. The `switch` statement needs another case for `'image/webp'`. A quick test confirmed that `saveCanvas('myCanvas.webp')` outputs a file with the MIME type `image/png`.

**Comment by starzonmyarmz** [comment]
Updated p5.js library: https://github.com/processing/p5.js/pull/7140.

**Comment by Qianqianye** [comment]
Thanks @starzonmyarmz. We will handle this in the PR on p5.js library repo https://github.com/processing/p5.js/pull/7140. I will close this one for organizational purpose.

**Pull request closed without merging**
