### PR TITLE
Debugging tutorial is ready!!!!

### PR DESCRIPTION
**Pull request by tegacodes**
Please review and merge if everything is cool?
This pull request also has the new structure for the tutorials page.

### CODE REVIEW

**Comment by tegacodes** [comment]
Note that I have also added in a bunch of new image classes for the tutorials to the main.css file of the page.  These are all new classes.. hope it doesnt mess anything else up.

**Comment by tchoi8** [comment]
it looks like this is not the latest one we worked on. I believe this is the latest version. https://github.com/tegacodes/p5.js-website/tree/mybranch/tutorials/debugging

**Comment by lmccart** [comment]
thanks! this look right? http://p5js.org/tutorials/debugging/
I'm just doing some last tweaks, the I'll tweet it out from the p5xjs account!
it looks soo great you guys! <3

**Comment by tchoi8** [comment]
yeah awesome! i think the images that are positioned between blocks of text (like http://p5js.org/tutorials/debugging/assets/1-0.jpg) need to be smaller. The images are a bit pixelated at the moment. Before you announce it, can Jason and I have final look on images?

**Comment by tegacodes** [comment]
Yep that's it.

Nice one.

On 19 October 2015 at 10:48, Lauren McCarthy <notifications@github.com>
wrote:

> thanks! this look right? http://p5js.org/tutorials/debugging/
> I'm just doing some last tweaks, the I'll tweet it out from the p5xjs
> account!
> it looks soo great you guys! <3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/178#issuecomment-149237520>
> .
>



-- 
Tega Brain

US: +1 347-259-3073
AUS: +61 411-158-731
www.tegabrain.com
@tegabrain <https://twitter.com/tegabrain>

**Comment by tegacodes** [comment]
taeyoon if you send me a list of the changes you want. I can change the
markdown. Is that the easiest way to do this?

On 19 October 2015 at 10:53, Taeyoon Choi <notifications@github.com> wrote:

> yeah awesome! i think the images that are positioned between blocks of
> text (like http://p5js.org/tutorials/debugging/assets/1-0.jpg) need to be
> smaller. The images are a bit pixelated at the moment. Before you announce
> it, can Jason and I have final look on images?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/178#issuecomment-149238666>
> .
>



-- 
Tega Brain

US: +1 347-259-3073
AUS: +61 411-158-731
www.tegabrain.com
@tegabrain <https://twitter.com/tegabrain>

**Comment by lmccart** [comment]
hey im going through and cleaning up the html right now, so if you can hold off on changing until I finish that (~20 mins), then pull the latest from p5.js master, we can avoid merge conflicts.

**Comment by tchoi8** [comment]
right on. we will wait! the image pixelation might be due to html/ css, so it might get fixed after lauren's edits. also i see some spelling errors like "spend allot of time" on chapter 0. :)

**Comment by lmccart** [comment]
ok go ahead. I just made some small changes to html and added targets for the anchors so you can now link to individual sections. I also fixed "allot" but haven't scanned for other spelling errors.

**Comment by tchoi8** [comment]
great. the images look good now. The only thing would be that on the http://p5js.org/tutorials/ page, it says (Beginners guide to debugging). In the tutorial, we say "This is a field guide for debugging for everyone". For consistency, can we say  A field guide for debugging for everyone. ?

**Comment by tegacodes** [comment]
Are the images fixed Taeyoon?

On 19 October 2015 at 11:08, Lauren McCarthy <notifications@github.com>
wrote:

> ok go ahead. I just made some small changes to html and added targets for
> the anchors so you can now link to individual sections. I also fixed
> "allot" but haven't scanned for other spelling errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/178#issuecomment-149242989>
> .
>



-- 
Tega Brain

US: +1 347-259-3073
AUS: +61 411-158-731
www.tegabrain.com
@tegabrain <https://twitter.com/tegabrain>

**Comment by lmccart** [comment]
right now it says "Field Guide to Debugging." should I change to "Field Guide to Debugging for Everyone." ?

**Comment by tchoi8** [comment]
Field Guide to Debugging for Everyone sounds good. 
yes. the images look good!

**Comment by lmccart** [comment]
ok, so we're good to tweet? or do you want to wait for jason to have a look as well?

**Comment by tchoi8** [comment]
i think Jason will be happy with this. and we can always make edits, revisions in the future. its good to tweet in my opinion

**Comment by luisaph** [comment]
looks great!!
love the new images + organization, and getting rid of 'vandal' too.
and didn't see any typos or anything.







On Mon, Oct 19, 2015 at 11:44 AM, Lauren McCarthy <notifications@github.com>
wrote:

> ok, so we're good to tweet? or do you want to wait for jason to have a
> look as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/processing/p5.js-website/pull/178#issuecomment-149253924>
> .
>



-- 

www.luisaph.com

**Pull request merged**
