### PR TITLE
Fix reference search index

### PR DESCRIPTION
**Pull request by stalgiag**
addresses #458 

This PR fixes an issue where methods with the same name were overwriting each other in the search index due to ignoring class names. This PR does the following:

- Adds method class names into relevant reference search indices
- Adds parentheses to methods in the search index for a more consistent appearance across the site
- Adds aliases to reference items that have a class or parentheses so they still rank high in searches without those elements included
- Adds a set of unit tests that ensures the above

~~Will request review after CI build finishes~~

### CODE REVIEW

**Comment by stalgiag** [comment]
Also, I was hoping to add @meezwhite as a reviewer but the repository settings don't allow review requests from people without a maintainer role.

I requested a review from three maintainers just as a way of flagging. One reviewer is likely enough. Thanks!

**Review by davepagurek — APPROVED** [review]
This looks good to me, thanks @stalgiag!

**Comment by Qianqianye** [comment]
Thanks @stalgiag!

**Comment by meezwhite** [comment]
Looks great! Thanks @stalgiag!

**Pull request merged**
