### PR TITLE
August Front Page

### PR DESCRIPTION
**Pull request by CICILIU**
August Front Page Featured work from Sarah

### CODE REVIEW

**Comment by sarahgp** [comment]
Hey guys,

This is really great and I am so excited to be on the front page. It seems like the responsiveness is broken somehow tho: it should redraw when it is resized. I suspect it is because it is in an iframe? Is there a way to fix this?

**Comment by sarahgp** [comment]
The implementation on d3-p5 cookbook redraws responsively: http://sciutoalex.github.io/p5-D3-cookbook/recipes-beginner/voronoi-interactive/

**Comment by lmccart** [comment]
Indeed, it was because of the iframe. I just changed things around so it's now building directly on the page instead of in an iframe. Let me know if you see any other issues.

@CICILIU I deviated a bit from how we normally add sketches to make this work, let's talk before you add the September one to change it back to how it was.

**Comment by sarahgp** [comment]
Thank you much!!

**Pull request merged**
