### PR TITLE
Add creative commons badge to examples

### PR DESCRIPTION
**Pull request by davepagurek**
Adds a badge + link to the CC license for examples below the code embed on example pages.

image

### CODE REVIEW

**Comment by Qianqianye** [comment]
Thanks @davepagurek!
Hi @xinemata, I will merge this if it looks good to you. I will also update the people page after we have more confirmed plan.

**Comment by xinemata** [comment]
Hi @Qianqianye and @davepagurek, this looks great overall. A minor note I have is if we can break Processing Foundation into its own hyperlink? 

For example, `<a href="/people/">p5.js Contributors</a> and the <a href="https://processingfoundation.org/people">Processing Foundation</a>`

**Comment by xinemata** [comment]
@davepagurek @Qianqianye – actually, since the [contributor list on the p5.js repo](https://github.com/processing/p5.js?tab=readme-ov-file#contributors) seems to be more up-to-date than the [p5.js people page](https://p5js.org/people/), maybe we should use this as the default link to attribute p5.js contributors?

**Comment by Qianqianye** [comment]
Thanks @davepagurek and @xinemata. I updated the link to the p5.js website 'People' page for now after a conversation with @xinemata. Later, we will add the following to the people page:
- an instruction to add contributors to the list
- a section for p5.js website design contributors

**Pull request merged**
