### PR TITLE
Mybranch

### PR DESCRIPTION
**Pull request by tegacodes**
Draft of debugging tutorial. This is ready for publishing so that final public review can happen.

### CODE REVIEW

**Comment by tchoi8** [comment]
hey! sorry for late reply on the previous email. I  had some more edits made but been swamped with work. I will review this and also add edits.  Can we shoot for pushing it out next weekendish?

**Comment by lmccart** [comment]
so.. should I merge this or no?

**Comment by lmccart** [comment]
Hi, what's the status on this? I'd love to merge it in before school starts. Anything I can do to help?

**Comment by tchoi8** [comment]
we closed this and made a new pull request.

**Pull request closed without merging**
